py3: migrate deb build

diff --git a/debian/preinst b/debian/preinst
--- a/debian/preinst
+++ b/debian/preinst
@@ -4,10 +4,35 @@
 
 set -e
 
+# Check command result
+# $1: command result (usually $?)
+# $2: awaited command result
+checkResult() {
+    if [ $1 -ne $2 ]
+    then
+        echo "Error occured. Please check command output."
+        exit 1
+    fi  
+}
+
 case "$1" in
-    install)
-        #nothing to preinstall here.
-        #python dependencies are installed by cleepos upgrade process
+    install | upgrade)
+        # install pip (or upgrade if necessary)
+        echo "Installing pip..."
+        wget --no-check-certificate "https://bootstrap.pypa.io/get-pip.py" -O /tmp/get-pip.py
+        checkResult $? 0
+        python3 /tmp/get-pip.py --trusted-host pypi.python.org
+        checkResult $? 0
+        rm -f /tmp/get-pip.py
+        echo "Done"
+        echo ""
+
+        # install python dependencies
+        echo "Installing python dependencies..."
+        pip3 install --no-cache-dir --trusted-host pypi.python.org "future==0.18.2" "six==1.14.0" "gevent==1.4.0" "bottle==0.12.18" "pyre-gevent==0.2.3" "netifaces==0.10.9" "uptime==3.0.1" "urllib3==1.25.9" "psutil==5.7.0" "passlib==1.7.2" "simplejson==3.17.0" "pytz==2020.1" "reverse-geocode==1.4" "timezonefinder==4.2.0" "tzlocal==2.0.0" "sentry-sdk==0.14.3"
+        checkResult $? 0
+        echo "Done"
+        echo ""
         ;; 
 
     *)
